### ISSUE TITLE
How would I get it to talk randomly?

### ISSUE THREAD

**Issue by unslyu** [adi-panda/Kuebiko#4]
How would I get it to talk randomly to fill dead silence and talk about how their day was, tell a story, etc. and not just only rely on Twitch chat?

I would appreciate if someone could help me with this!

**Comment by unslyu** [comment]
I've figured it out!

You can use TwitchIO Routines and set it to run the AI and make it to run every few seconds.

Probably not the smartest way to doing this but it works!

**Comment by dontaco2000** [comment]
Could you tell me how you achieved this because I tried to get it to do a response when the closed captions were silent for a certain duration because I co-stream with my vtuber with her as an assistant but I couldn't figure it out. I thought if I could figure that out, I could figure out how to also activate a conversation with my voice via closed captions as well. I had a good idea but not enough knowhow to use it.
